/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1GetUserReviewsRequestContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1GetUserReviewsRequestContract {
    /**
     * The productIds property.
     */
    @JsonProperty(value = "productIds")
    private List<String> productIds;

    /**
     * Get the productIds value.
     *
     * @return the productIds value
     */
    public List<String> productIds() {
        return this.productIds;
    }

    /**
     * Set the productIds value.
     *
     * @param productIds the productIds value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1GetUserReviewsRequestContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1GetUserReviewsRequestContract withProductIds(List<String> productIds) {
        this.productIds = productIds;
        return this;
    }

}
