/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

//import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract {
    /**
     * The catalogId property.
     */
    @JsonProperty(value = "catalogId")
    private Integer catalogId;

    /**
     * The rootId property.
     */
    @JsonProperty(value = "rootId")
    private String rootId;

    /**
     * The parentId property.
     */
    @JsonProperty(value = "parentId")
    private String parentId;

    /**
     * The commentId property.
     */
    @JsonProperty(value = "commentId")
    private String commentId;

    /**
     * The authorName property.
     */
    @JsonProperty(value = "authorName")
    private String authorName;

    /**
     * The replies property.
     */
    @JsonProperty(value = "replies")
    private Integer replies;

    /**
     * The commentText property.
     */
    @JsonProperty(value = "commentText")
    private String commentText;

    /**
     * The submittedDateTime property.
     */
    @JsonProperty(value = "submittedDateTime")
    private String submittedDateTime;

    /**
     * The isTakenDown property.
     */
    @JsonProperty(value = "isTakenDown")
    private Boolean isTakenDown;

    /**
     * The takenDownReason property.
     */
    @JsonProperty(value = "takenDownReason")
    private Integer takenDownReason;

    /**
     * The takenDownTime property.
     */
    @JsonProperty(value = "takenDownTime")
    private String takenDownTime;

    /**
     * The violationsFound property.
     */
    @JsonProperty(value = "violationsFound")
    private Boolean violationsFound;

    /**
     * The market property.
     */
    @JsonProperty(value = "market")
    private String market;

    /**
     * The locale property.
     */
    @JsonProperty(value = "locale")
    private String locale;

    /**
     * The version property.
     */
    @JsonProperty(value = "version")
    private Long version;

    /**
     * The isCurrentUsersComment property.
     */
    @JsonProperty(value = "isCurrentUsersComment")
    private Boolean isCurrentUsersComment;

    /**
     * Get the catalogId value.
     *
     * @return the catalogId value
     */
    public Integer catalogId() {
        return this.catalogId;
    }

    /**
     * Set the catalogId value.
     *
     * @param catalogId the catalogId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
        return this;
    }

    /**
     * Get the rootId value.
     *
     * @return the rootId value
     */
    public String rootId() {
        return this.rootId;
    }

    /**
     * Set the rootId value.
     *
     * @param rootId the rootId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withRootId(String rootId) {
        this.rootId = rootId;
        return this;
    }

    /**
     * Get the parentId value.
     *
     * @return the parentId value
     */
    public String parentId() {
        return this.parentId;
    }

    /**
     * Set the parentId value.
     *
     * @param parentId the parentId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withParentId(String parentId) {
        this.parentId = parentId;
        return this;
    }

    /**
     * Get the commentId value.
     *
     * @return the commentId value
     */
    public String commentId() {
        return this.commentId;
    }

    /**
     * Set the commentId value.
     *
     * @param commentId the commentId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withCommentId(String commentId) {
        this.commentId = commentId;
        return this;
    }

    /**
     * Get the authorName value.
     *
     * @return the authorName value
     */
    public String authorName() {
        return this.authorName;
    }

    /**
     * Set the authorName value.
     *
     * @param authorName the authorName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withAuthorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

    /**
     * Get the replies value.
     *
     * @return the replies value
     */
    public Integer replies() {
        return this.replies;
    }

    /**
     * Set the replies value.
     *
     * @param replies the replies value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withReplies(Integer replies) {
        this.replies = replies;
        return this;
    }

    /**
     * Get the commentText value.
     *
     * @return the commentText value
     */
    public String commentText() {
        return this.commentText;
    }

    /**
     * Set the commentText value.
     *
     * @param commentText the commentText value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withCommentText(String commentText) {
        this.commentText = commentText;
        return this;
    }

    /**
     * Get the submittedDateTime value.
     *
     * @return the submittedDateTime value
     */
    public String submittedDateTime() {
        return this.submittedDateTime;
    }

    /**
     * Set the submittedDateTime value.
     *
     * @param submittedDateTime the submittedDateTime value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withSubmittedDateTime(String submittedDateTime) {
        this.submittedDateTime = submittedDateTime;
        return this;
    }

    /**
     * Get the isTakenDown value.
     *
     * @return the isTakenDown value
     */
    public Boolean isTakenDown() {
        return this.isTakenDown;
    }

    /**
     * Set the isTakenDown value.
     *
     * @param isTakenDown the isTakenDown value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withIsTakenDown(Boolean isTakenDown) {
        this.isTakenDown = isTakenDown;
        return this;
    }

    /**
     * Get the takenDownReason value.
     *
     * @return the takenDownReason value
     */
    public Integer takenDownReason() {
        return this.takenDownReason;
    }

    /**
     * Set the takenDownReason value.
     *
     * @param takenDownReason the takenDownReason value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withTakenDownReason(Integer takenDownReason) {
        this.takenDownReason = takenDownReason;
        return this;
    }

    /**
     * Get the takenDownTime value.
     *
     * @return the takenDownTime value
     */
    public String takenDownTime() {
        return this.takenDownTime;
    }

    /**
     * Set the takenDownTime value.
     *
     * @param takenDownTime the takenDownTime value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withTakenDownTime(String takenDownTime) {
        this.takenDownTime = takenDownTime;
        return this;
    }

    /**
     * Get the violationsFound value.
     *
     * @return the violationsFound value
     */
    public Boolean violationsFound() {
        return this.violationsFound;
    }

    /**
     * Set the violationsFound value.
     *
     * @param violationsFound the violationsFound value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withViolationsFound(Boolean violationsFound) {
        this.violationsFound = violationsFound;
        return this;
    }

    /**
     * Get the market value.
     *
     * @return the market value
     */
    public String market() {
        return this.market;
    }

    /**
     * Set the market value.
     *
     * @param market the market value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withMarket(String market) {
        this.market = market;
        return this;
    }

    /**
     * Get the locale value.
     *
     * @return the locale value
     */
    public String locale() {
        return this.locale;
    }

    /**
     * Set the locale value.
     *
     * @param locale the locale value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withLocale(String locale) {
        this.locale = locale;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public Long version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withVersion(Long version) {
        this.version = version;
        return this;
    }

    /**
     * Get the isCurrentUsersComment value.
     *
     * @return the isCurrentUsersComment value
     */
    public Boolean isCurrentUsersComment() {
        return this.isCurrentUsersComment;
    }

    /**
     * Set the isCurrentUsersComment value.
     *
     * @param isCurrentUsersComment the isCurrentUsersComment value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1CommentContract withIsCurrentUsersComment(Boolean isCurrentUsersComment) {
        this.isCurrentUsersComment = isCurrentUsersComment;
        return this;
    }

}
