/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagedObjectLikeContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagedObjectLikeContract {
    /**
     * The pagingInfo property.
     */
    @JsonProperty(value = "pagingInfo")
    private MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract pagingInfo;

    /**
     * The items property.
     */
    @JsonProperty(value = "items")
    private List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract> items;

    /**
     * Get the pagingInfo value.
     *
     * @return the pagingInfo value
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract pagingInfo() {
        return this.pagingInfo;
    }

    /**
     * Set the pagingInfo value.
     *
     * @param pagingInfo the pagingInfo value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagedObjectLikeContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagedObjectLikeContract withPagingInfo(MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract pagingInfo) {
        this.pagingInfo = pagingInfo;
        return this;
    }

    /**
     * Get the items value.
     *
     * @return the items value
     */
    public List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract> items() {
        return this.items;
    }

    /**
     * Set the items value.
     *
     * @param items the items value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagedObjectLikeContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagedObjectLikeContract withItems(List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract> items) {
        this.items = items;
        return this;
    }

}
