/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract {
    /**
     * The objectId property.
     */
    @JsonProperty(value = "objectId")
    private String objectId;

    /**
     * The liked property.
     */
    @JsonProperty(value = "liked")
    private Boolean liked;

    /**
     * Get the objectId value.
     *
     * @return the objectId value
     */
    public String objectId() {
        return this.objectId;
    }

    /**
     * Set the objectId value.
     *
     * @param objectId the objectId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract withObjectId(String objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Get the liked value.
     *
     * @return the liked value
     */
    public Boolean liked() {
        return this.liked;
    }

    /**
     * Set the liked value.
     *
     * @param liked the liked value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract withLiked(Boolean liked) {
        this.liked = liked;
        return this;
    }

}
