/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

//import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract {
    /**
     * The topReviewerSinceDate property.
     */
    @JsonProperty(value = "topReviewerSinceDate")
    private String topReviewerSinceDate;

    /**
     * The reviewerName property.
     */
    @JsonProperty(value = "reviewerName")
    private String reviewerName;

    /**
     * The reviewerRank property.
     */
    @JsonProperty(value = "reviewerRank")
    private Long reviewerRank;

    /**
     * The percentageThoughtful property.
     */
    @JsonProperty(value = "percentageThoughtful")
    private Double percentageThoughtful;

    /**
     * The followed property.
     */
    @JsonProperty(value = "followed")
    private Boolean followed;

    /**
     * The reviewCount property.
     */
    @JsonProperty(value = "reviewCount")
    private Integer reviewCount;

    /**
     * The firstReviewDate property.
     */
    @JsonProperty(value = "firstReviewDate")
    private String firstReviewDate;

    /**
     * The lastReviewDate property.
     */
    @JsonProperty(value = "lastReviewDate")
    private String lastReviewDate;

    /**
     * The followerCount property.
     */
    @JsonProperty(value = "followerCount")
    private Integer followerCount;

    /**
     * The helpfulnessVoteCountPositive property.
     */
    @JsonProperty(value = "helpfulnessVoteCountPositive")
    private Integer helpfulnessVoteCountPositive;

    /**
     * The helpfulnessVoteCountNegative property.
     */
    @JsonProperty(value = "helpfulnessVoteCountNegative")
    private Integer helpfulnessVoteCountNegative;

    /**
     * Get the topReviewerSinceDate value.
     *
     * @return the topReviewerSinceDate value
     */
    public String topReviewerSinceDate() {
        return this.topReviewerSinceDate;
    }

    /**
     * Set the topReviewerSinceDate value.
     *
     * @param topReviewerSinceDate the topReviewerSinceDate value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withTopReviewerSinceDate(String topReviewerSinceDate) {
        this.topReviewerSinceDate = topReviewerSinceDate;
        return this;
    }

    /**
     * Get the reviewerName value.
     *
     * @return the reviewerName value
     */
    public String reviewerName() {
        return this.reviewerName;
    }

    /**
     * Set the reviewerName value.
     *
     * @param reviewerName the reviewerName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withReviewerName(String reviewerName) {
        this.reviewerName = reviewerName;
        return this;
    }

    /**
     * Get the reviewerRank value.
     *
     * @return the reviewerRank value
     */
    public Long reviewerRank() {
        return this.reviewerRank;
    }

    /**
     * Set the reviewerRank value.
     *
     * @param reviewerRank the reviewerRank value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withReviewerRank(Long reviewerRank) {
        this.reviewerRank = reviewerRank;
        return this;
    }

    /**
     * Get the percentageThoughtful value.
     *
     * @return the percentageThoughtful value
     */
    public Double percentageThoughtful() {
        return this.percentageThoughtful;
    }

    /**
     * Set the percentageThoughtful value.
     *
     * @param percentageThoughtful the percentageThoughtful value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withPercentageThoughtful(Double percentageThoughtful) {
        this.percentageThoughtful = percentageThoughtful;
        return this;
    }

    /**
     * Get the followed value.
     *
     * @return the followed value
     */
    public Boolean followed() {
        return this.followed;
    }

    /**
     * Set the followed value.
     *
     * @param followed the followed value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withFollowed(Boolean followed) {
        this.followed = followed;
        return this;
    }

    /**
     * Get the reviewCount value.
     *
     * @return the reviewCount value
     */
    public Integer reviewCount() {
        return this.reviewCount;
    }

    /**
     * Set the reviewCount value.
     *
     * @param reviewCount the reviewCount value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withReviewCount(Integer reviewCount) {
        this.reviewCount = reviewCount;
        return this;
    }

    /**
     * Get the firstReviewDate value.
     *
     * @return the firstReviewDate value
     */
    public String firstReviewDate() {
        return this.firstReviewDate;
    }

    /**
     * Set the firstReviewDate value.
     *
     * @param firstReviewDate the firstReviewDate value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withFirstReviewDate(String firstReviewDate) {
        this.firstReviewDate = firstReviewDate;
        return this;
    }

    /**
     * Get the lastReviewDate value.
     *
     * @return the lastReviewDate value
     */
    public String lastReviewDate() {
        return this.lastReviewDate;
    }

    /**
     * Set the lastReviewDate value.
     *
     * @param lastReviewDate the lastReviewDate value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withLastReviewDate(String lastReviewDate) {
        this.lastReviewDate = lastReviewDate;
        return this;
    }

    /**
     * Get the followerCount value.
     *
     * @return the followerCount value
     */
    public Integer followerCount() {
        return this.followerCount;
    }

    /**
     * Set the followerCount value.
     *
     * @param followerCount the followerCount value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withFollowerCount(Integer followerCount) {
        this.followerCount = followerCount;
        return this;
    }

    /**
     * Get the helpfulnessVoteCountPositive value.
     *
     * @return the helpfulnessVoteCountPositive value
     */
    public Integer helpfulnessVoteCountPositive() {
        return this.helpfulnessVoteCountPositive;
    }

    /**
     * Set the helpfulnessVoteCountPositive value.
     *
     * @param helpfulnessVoteCountPositive the helpfulnessVoteCountPositive value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withHelpfulnessVoteCountPositive(Integer helpfulnessVoteCountPositive) {
        this.helpfulnessVoteCountPositive = helpfulnessVoteCountPositive;
        return this;
    }

    /**
     * Get the helpfulnessVoteCountNegative value.
     *
     * @return the helpfulnessVoteCountNegative value
     */
    public Integer helpfulnessVoteCountNegative() {
        return this.helpfulnessVoteCountNegative;
    }

    /**
     * Set the helpfulnessVoteCountNegative value.
     *
     * @param helpfulnessVoteCountNegative the helpfulnessVoteCountNegative value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract withHelpfulnessVoteCountNegative(Integer helpfulnessVoteCountNegative) {
        this.helpfulnessVoteCountNegative = helpfulnessVoteCountNegative;
        return this;
    }

}
