/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.UUID;
//import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract
 * model.
 */
@JsonIgnoreProperties(ignoreUnknown=true)
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract {
    /**
     * The productId property.
     */
    @JsonProperty(value = "ProductId")
    private String productId;

    /**
     * The userName property.
     */
    @JsonProperty(value = "UserName")
    private String userName;

    /**
     * The rating property.
     */
    @JsonProperty(value = "Rating")
    private Integer rating;

    /**
     * The market property.
     */
    @JsonProperty(value = "Market")
    private String market;

    /**
     * The locale property.
     */
    @JsonProperty(value = "Locale")
    private String locale;

    /**
     * The helpfulnessVotes property.
     */
    @JsonProperty(value = "HelpfulnessVotes")
    private Double helpfulnessVotes;

    /**
     * The helpfulPositive property.
     */
    @JsonProperty(value = "HelpfulPositive")
    private Integer helpfulPositive;

    /**
     * The helpfulNegative property.
     */
    @JsonProperty(value = "HelpfulNegative")
    private Integer helpfulNegative;

    /**
     * The catalogId property.
     */
    @JsonProperty(value = "CatalogId")
    private Integer catalogId;

    /**
     * The reviewId property.
     */
    @JsonProperty(value = "ReviewId")
    private UUID reviewId;

    /**
     * The reviewText property.
     */
    @JsonProperty(value = "ReviewText")
    private String reviewText;

    /**
     * The title property.
     */
    @JsonProperty(value = "Title")
    private String title;

    /**
     * The submittedDateTime property.
     */
    @JsonProperty(value = "SubmittedDateTime")
    private String submittedDateTime;

    /**
     * The productTrial property.
     */
    @JsonProperty(value = "ProductTrial")
    private Boolean productTrial;

    /**
     * The skuId property.
     */
    @JsonProperty(value = "SkuId")
    private String skuId;

    /**
     * The productVersion property.
     */
    @JsonProperty(value = "ProductVersion")
    private String productVersion;

    /**
     * The isTakenDown property.
     */
    @JsonProperty(value = "IsTakenDown")
    private Boolean isTakenDown;

    /**
     * The violationsFound property.
     */
    @JsonProperty(value = "ViolationsFound")
    private Boolean violationsFound;

    /**
     * The userResponse property.
     */
    @JsonProperty(value = "UserResponse")
    private MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserResponseContract userResponse;

    /**
     * The isPublished property.
     */
    @JsonProperty(value = "IsPublished")
    private Boolean isPublished;

    /**
     * The isRevised property.
     */
    @JsonProperty(value = "IsRevised")
    private Boolean isRevised;

    /**
     * The updatedSinceResponse property.
     */
    @JsonProperty(value = "UpdatedSinceResponse")
    private Boolean updatedSinceResponse;

    /**
     * The isAppInstalled property.
     */
    @JsonProperty(value = "IsAppInstalled")
    private Boolean isAppInstalled;

    /**
     * The deviceModel property.
     */
    @JsonProperty(value = "DeviceModel")
    private String deviceModel;

    /**
     * The packageFullName property.
     */
    @JsonProperty(value = "PackageFullName")
    private String packageFullName;

    /**
     * The packageVersion property.
     */
    @JsonProperty(value = "PackageVersion")
    private String packageVersion;

    /**
     * The deviceFamily property.
     */
    @JsonProperty(value = "DeviceFamily")
    private String deviceFamily;

    /**
     * The hasEntitlement property.
     */
    @JsonProperty(value = "HasEntitlement")
    private Boolean hasEntitlement;

    /**
     * The reviewerRank property.
     */
    @JsonProperty(value = "ReviewerRank")
    private Long reviewerRank;

    /**
     * The usageData property.
     */
    @JsonProperty(value = "UsageData")
    private MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract usageData;

    /**
     * The ipAddress property.
     */
    @JsonProperty(value = "IpAddress")
    private String ipAddress;

    /**
     * The xType property.
     */
    @JsonProperty(value = "XType")
    private String xType;

    /**
     * The takenDownReason property.
     */
    @JsonProperty(value = "TakenDownReason")
    private Integer takenDownReason;

    /**
     * The takenDownTime property.
     */
    @JsonProperty(value = "TakenDownTime")
    private String takenDownTime;

    /**
     * The deviceId property.
     */
    @JsonProperty(value = "DeviceId")
    private String deviceId;

    /**
     * The osVersion property.
     */
    @JsonProperty(value = "OsVersion")
    private String osVersion;

    /**
     * Get the productId value.
     *
     * @return the productId value
     */
    public String productId() {
        return this.productId;
    }

    /**
     * Set the productId value.
     *
     * @param productId the productId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withProductId(String productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Get the userName value.
     *
     * @return the userName value
     */
    public String userName() {
        return this.userName;
    }

    /**
     * Set the userName value.
     *
     * @param userName the userName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Get the rating value.
     *
     * @return the rating value
     */
    public Integer rating() {
        return this.rating;
    }

    /**
     * Set the rating value.
     *
     * @param rating the rating value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    /**
     * Get the market value.
     *
     * @return the market value
     */
    public String market() {
        return this.market;
    }

    /**
     * Set the market value.
     *
     * @param market the market value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withMarket(String market) {
        this.market = market;
        return this;
    }

    /**
     * Get the locale value.
     *
     * @return the locale value
     */
    public String locale() {
        return this.locale;
    }

    /**
     * Set the locale value.
     *
     * @param locale the locale value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withLocale(String locale) {
        this.locale = locale;
        return this;
    }

    /**
     * Get the helpfulnessVotes value.
     *
     * @return the helpfulnessVotes value
     */
    public Double helpfulnessVotes() {
        return this.helpfulnessVotes;
    }

    /**
     * Set the helpfulnessVotes value.
     *
     * @param helpfulnessVotes the helpfulnessVotes value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withHelpfulnessVotes(Double helpfulnessVotes) {
        this.helpfulnessVotes = helpfulnessVotes;
        return this;
    }

    /**
     * Get the helpfulPositive value.
     *
     * @return the helpfulPositive value
     */
    public Integer helpfulPositive() {
        return this.helpfulPositive;
    }

    /**
     * Set the helpfulPositive value.
     *
     * @param helpfulPositive the helpfulPositive value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withHelpfulPositive(Integer helpfulPositive) {
        this.helpfulPositive = helpfulPositive;
        return this;
    }

    /**
     * Get the helpfulNegative value.
     *
     * @return the helpfulNegative value
     */
    public Integer helpfulNegative() {
        return this.helpfulNegative;
    }

    /**
     * Set the helpfulNegative value.
     *
     * @param helpfulNegative the helpfulNegative value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withHelpfulNegative(Integer helpfulNegative) {
        this.helpfulNegative = helpfulNegative;
        return this;
    }

    /**
     * Get the catalogId value.
     *
     * @return the catalogId value
     */
    public Integer catalogId() {
        return this.catalogId;
    }

    /**
     * Set the catalogId value.
     *
     * @param catalogId the catalogId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
        return this;
    }

    /**
     * Get the reviewId value.
     *
     * @return the reviewId value
     */
    public UUID reviewId() {
        return this.reviewId;
    }

    /**
     * Set the reviewId value.
     *
     * @param reviewId the reviewId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withReviewId(UUID reviewId) {
        this.reviewId = reviewId;
        return this;
    }

    /**
     * Get the reviewText value.
     *
     * @return the reviewText value
     */
    public String reviewText() {
        return this.reviewText;
    }

    /**
     * Set the reviewText value.
     *
     * @param reviewText the reviewText value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withReviewText(String reviewText) {
        this.reviewText = reviewText;
        return this;
    }

    /**
     * Get the title value.
     *
     * @return the title value
     */
    public String title() {
        return this.title;
    }

    /**
     * Set the title value.
     *
     * @param title the title value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get the submittedDateTime value.
     *
     * @return the submittedDateTime value
     */
    public String submittedDateTime() {
        return this.submittedDateTime;
    }

    /**
     * Set the submittedDateTime value.
     *
     * @param submittedDateTime the submittedDateTime value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withSubmittedDateTime(String submittedDateTime) {
        this.submittedDateTime = submittedDateTime;
        return this;
    }

    /**
     * Get the productTrial value.
     *
     * @return the productTrial value
     */
    public Boolean productTrial() {
        return this.productTrial;
    }

    /**
     * Set the productTrial value.
     *
     * @param productTrial the productTrial value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withProductTrial(Boolean productTrial) {
        this.productTrial = productTrial;
        return this;
    }

    /**
     * Get the skuId value.
     *
     * @return the skuId value
     */
    public String skuId() {
        return this.skuId;
    }

    /**
     * Set the skuId value.
     *
     * @param skuId the skuId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withSkuId(String skuId) {
        this.skuId = skuId;
        return this;
    }

    /**
     * Get the productVersion value.
     *
     * @return the productVersion value
     */
    public String productVersion() {
        return this.productVersion;
    }

    /**
     * Set the productVersion value.
     *
     * @param productVersion the productVersion value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withProductVersion(String productVersion) {
        this.productVersion = productVersion;
        return this;
    }

    /**
     * Get the isTakenDown value.
     *
     * @return the isTakenDown value
     */
    public Boolean isTakenDown() {
        return this.isTakenDown;
    }

    /**
     * Set the isTakenDown value.
     *
     * @param isTakenDown the isTakenDown value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withIsTakenDown(Boolean isTakenDown) {
        this.isTakenDown = isTakenDown;
        return this;
    }

    /**
     * Get the violationsFound value.
     *
     * @return the violationsFound value
     */
    public Boolean violationsFound() {
        return this.violationsFound;
    }

    /**
     * Set the violationsFound value.
     *
     * @param violationsFound the violationsFound value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withViolationsFound(Boolean violationsFound) {
        this.violationsFound = violationsFound;
        return this;
    }

    /**
     * Get the userResponse value.
     *
     * @return the userResponse value
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserResponseContract userResponse() {
        return this.userResponse;
    }

    /**
     * Set the userResponse value.
     *
     * @param userResponse the userResponse value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withUserResponse(MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserResponseContract userResponse) {
        this.userResponse = userResponse;
        return this;
    }

    /**
     * Get the isPublished value.
     *
     * @return the isPublished value
     */
    public Boolean isPublished() {
        return this.isPublished;
    }

    /**
     * Set the isPublished value.
     *
     * @param isPublished the isPublished value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
        return this;
    }

    /**
     * Get the isRevised value.
     *
     * @return the isRevised value
     */
    public Boolean isRevised() {
        return this.isRevised;
    }

    /**
     * Set the isRevised value.
     *
     * @param isRevised the isRevised value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withIsRevised(Boolean isRevised) {
        this.isRevised = isRevised;
        return this;
    }

    /**
     * Get the updatedSinceResponse value.
     *
     * @return the updatedSinceResponse value
     */
    public Boolean updatedSinceResponse() {
        return this.updatedSinceResponse;
    }

    /**
     * Set the updatedSinceResponse value.
     *
     * @param updatedSinceResponse the updatedSinceResponse value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withUpdatedSinceResponse(Boolean updatedSinceResponse) {
        this.updatedSinceResponse = updatedSinceResponse;
        return this;
    }

    /**
     * Get the isAppInstalled value.
     *
     * @return the isAppInstalled value
     */
    public Boolean isAppInstalled() {
        return this.isAppInstalled;
    }

    /**
     * Set the isAppInstalled value.
     *
     * @param isAppInstalled the isAppInstalled value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withIsAppInstalled(Boolean isAppInstalled) {
        this.isAppInstalled = isAppInstalled;
        return this;
    }

    /**
     * Get the deviceModel value.
     *
     * @return the deviceModel value
     */
    public String deviceModel() {
        return this.deviceModel;
    }

    /**
     * Set the deviceModel value.
     *
     * @param deviceModel the deviceModel value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel;
        return this;
    }

    /**
     * Get the packageFullName value.
     *
     * @return the packageFullName value
     */
    public String packageFullName() {
        return this.packageFullName;
    }

    /**
     * Set the packageFullName value.
     *
     * @param packageFullName the packageFullName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withPackageFullName(String packageFullName) {
        this.packageFullName = packageFullName;
        return this;
    }

    /**
     * Get the packageVersion value.
     *
     * @return the packageVersion value
     */
    public String packageVersion() {
        return this.packageVersion;
    }

    /**
     * Set the packageVersion value.
     *
     * @param packageVersion the packageVersion value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withPackageVersion(String packageVersion) {
        this.packageVersion = packageVersion;
        return this;
    }

    /**
     * Get the deviceFamily value.
     *
     * @return the deviceFamily value
     */
    public String deviceFamily() {
        return this.deviceFamily;
    }

    /**
     * Set the deviceFamily value.
     *
     * @param deviceFamily the deviceFamily value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withDeviceFamily(String deviceFamily) {
        this.deviceFamily = deviceFamily;
        return this;
    }

    /**
     * Get the hasEntitlement value.
     *
     * @return the hasEntitlement value
     */
    public Boolean hasEntitlement() {
        return this.hasEntitlement;
    }

    /**
     * Set the hasEntitlement value.
     *
     * @param hasEntitlement the hasEntitlement value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withHasEntitlement(Boolean hasEntitlement) {
        this.hasEntitlement = hasEntitlement;
        return this;
    }

    /**
     * Get the reviewerRank value.
     *
     * @return the reviewerRank value
     */
    public Long reviewerRank() {
        return this.reviewerRank;
    }

    /**
     * Set the reviewerRank value.
     *
     * @param reviewerRank the reviewerRank value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withReviewerRank(Long reviewerRank) {
        this.reviewerRank = reviewerRank;
        return this;
    }

    /**
     * Get the usageData value.
     *
     * @return the usageData value
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract usageData() {
        return this.usageData;
    }

    /**
     * Set the usageData value.
     *
     * @param usageData the usageData value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withUsageData(MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract usageData) {
        this.usageData = usageData;
        return this;
    }

    /**
     * Get the ipAddress value.
     *
     * @return the ipAddress value
     */
    public String ipAddress() {
        return this.ipAddress;
    }

    /**
     * Set the ipAddress value.
     *
     * @param ipAddress the ipAddress value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        return this;
    }

    /**
     * Get the xType value.
     *
     * @return the xType value
     */
    public String xType() {
        return this.xType;
    }

    /**
     * Set the xType value.
     *
     * @param xType the xType value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withXType(String xType) {
        this.xType = xType;
        return this;
    }

    /**
     * Get the takenDownReason value.
     *
     * @return the takenDownReason value
     */
    public Integer takenDownReason() {
        return this.takenDownReason;
    }

    /**
     * Set the takenDownReason value.
     *
     * @param takenDownReason the takenDownReason value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withTakenDownReason(Integer takenDownReason) {
        this.takenDownReason = takenDownReason;
        return this;
    }

    /**
     * Get the takenDownTime value.
     *
     * @return the takenDownTime value
     */
    public String takenDownTime() {
        return this.takenDownTime;
    }

    /**
     * Set the takenDownTime value.
     *
     * @param takenDownTime the takenDownTime value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withTakenDownTime(String takenDownTime) {
        this.takenDownTime = takenDownTime;
        return this;
    }

    /**
     * Get the deviceId value.
     *
     * @return the deviceId value
     */
    public String deviceId() {
        return this.deviceId;
    }

    /**
     * Set the deviceId value.
     *
     * @param deviceId the deviceId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withDeviceId(String deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get the osVersion value.
     *
     * @return the osVersion value
     */
    public String osVersion() {
        return this.osVersion;
    }

    /**
     * Set the osVersion value.
     *
     * @param osVersion the osVersion value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewContract withOsVersion(String osVersion) {
        this.osVersion = osVersion;
        return this;
    }

}
