/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract {
    /**
     * The productId property.
     */
    @JsonProperty(value = "productId")
    private String productId;

    /**
     * The reviewId property.
     */
    @JsonProperty(value = "reviewId")
    private UUID reviewId;

    /**
     * The takenDown property.
     */
    @JsonProperty(value = "takenDown")
    private Boolean takenDown;

    /**
     * The nickname property.
     */
    @JsonProperty(value = "nickname")
    private String nickname;

    /**
     * The note property.
     */
    @JsonProperty(value = "note")
    private String note;

    /**
     * Get the productId value.
     *
     * @return the productId value
     */
    public String productId() {
        return this.productId;
    }

    /**
     * Set the productId value.
     *
     * @param productId the productId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract withProductId(String productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Get the reviewId value.
     *
     * @return the reviewId value
     */
    public UUID reviewId() {
        return this.reviewId;
    }

    /**
     * Set the reviewId value.
     *
     * @param reviewId the reviewId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract withReviewId(UUID reviewId) {
        this.reviewId = reviewId;
        return this;
    }

    /**
     * Get the takenDown value.
     *
     * @return the takenDown value
     */
    public Boolean takenDown() {
        return this.takenDown;
    }

    /**
     * Set the takenDown value.
     *
     * @param takenDown the takenDown value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract withTakenDown(Boolean takenDown) {
        this.takenDown = takenDown;
        return this;
    }

    /**
     * Get the nickname value.
     *
     * @return the nickname value
     */
    public String nickname() {
        return this.nickname;
    }

    /**
     * Set the nickname value.
     *
     * @param nickname the nickname value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract withNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * Get the note value.
     *
     * @return the note value
     */
    public String note() {
        return this.note;
    }

    /**
     * Set the note value.
     *
     * @param note the note value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitFavoriteReviewerContract withNote(String note) {
        this.note = note;
        return this;
    }

}
