/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SimilarReviewerProfilesContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SimilarReviewerProfilesContract {
    /**
     * The similarReviewerProfileList property.
     */
    @JsonProperty(value = "similarReviewerProfileList")
    private List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfileContract> similarReviewerProfileList;

    /**
     * Get the similarReviewerProfileList value.
     *
     * @return the similarReviewerProfileList value
     */
    public List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfileContract> similarReviewerProfileList() {
        return this.similarReviewerProfileList;
    }

    /**
     * Set the similarReviewerProfileList value.
     *
     * @param similarReviewerProfileList the similarReviewerProfileList value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SimilarReviewerProfilesContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SimilarReviewerProfilesContract withSimilarReviewerProfileList(List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfileContract> similarReviewerProfileList) {
        this.similarReviewerProfileList = similarReviewerProfileList;
        return this;
    }

}
