/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract {
    /**
     * The concernCategory property.
     */
    @JsonProperty(value = "concernCategory")
    private Long concernCategory;

    /**
     * The deviceId property.
     */
    @JsonProperty(value = "deviceId")
    private String deviceId;

    /**
     * The osVersion property.
     */
    @JsonProperty(value = "osVersion")
    private String osVersion;

    /**
     * Get the concernCategory value.
     *
     * @return the concernCategory value
     */
    public Long concernCategory() {
        return this.concernCategory;
    }

    /**
     * Set the concernCategory value.
     *
     * @param concernCategory the concernCategory value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract withConcernCategory(Long concernCategory) {
        this.concernCategory = concernCategory;
        return this;
    }

    /**
     * Get the deviceId value.
     *
     * @return the deviceId value
     */
    public String deviceId() {
        return this.deviceId;
    }

    /**
     * Set the deviceId value.
     *
     * @param deviceId the deviceId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract withDeviceId(String deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get the osVersion value.
     *
     * @return the osVersion value
     */
    public String osVersion() {
        return this.osVersion;
    }

    /**
     * Set the osVersion value.
     *
     * @param osVersion the osVersion value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReportReviewConcernContract withOsVersion(String osVersion) {
        this.osVersion = osVersion;
        return this;
    }

}
