/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

//import org.joda.time.DateTime;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfilesContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfilesContract {
    /**
     * The submittedDateTime property.
     */
    @JsonProperty(value = "submittedDateTime")
    private String submittedDateTime;

    /**
     * The topReviewerProfileList property.
     */
    @JsonProperty(value = "topReviewerProfileList")
    private List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract> topReviewerProfileList;

    /**
     * Get the submittedDateTime value.
     *
     * @return the submittedDateTime value
     */
    public String submittedDateTime() {
        return this.submittedDateTime;
    }

    /**
     * Set the submittedDateTime value.
     *
     * @param submittedDateTime the submittedDateTime value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfilesContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfilesContract withSubmittedDateTime(String submittedDateTime) {
        this.submittedDateTime = submittedDateTime;
        return this;
    }

    /**
     * Get the topReviewerProfileList value.
     *
     * @return the topReviewerProfileList value
     */
    public List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract> topReviewerProfileList() {
        return this.topReviewerProfileList;
    }

    /**
     * Set the topReviewerProfileList value.
     *
     * @param topReviewerProfileList the topReviewerProfileList value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfilesContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfilesContract withTopReviewerProfileList(List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1TopReviewerProfileContract> topReviewerProfileList) {
        this.topReviewerProfileList = topReviewerProfileList;
        return this;
    }

}
