/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

//import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract {
    /**
     * The catalogId property.
     */
    @JsonProperty(value = "catalogId")
    private Integer catalogId;

    /**
     * The objectId property.
     */
    @JsonProperty(value = "objectId")
    private String objectId;

    /**
     * The userName property.
     */
    @JsonProperty(value = "userName")
    private String userName;

    /**
     * The submittedDateTime property.
     */
    @JsonProperty(value = "submittedDateTime")
    private String submittedDateTime;

    /**
     * Get the catalogId value.
     *
     * @return the catalogId value
     */
    public Integer catalogId() {
        return this.catalogId;
    }

    /**
     * Set the catalogId value.
     *
     * @param catalogId the catalogId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract withCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
        return this;
    }

    /**
     * Get the objectId value.
     *
     * @return the objectId value
     */
    public String objectId() {
        return this.objectId;
    }

    /**
     * Set the objectId value.
     *
     * @param objectId the objectId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract withObjectId(String objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Get the userName value.
     *
     * @return the userName value
     */
    public String userName() {
        return this.userName;
    }

    /**
     * Set the userName value.
     *
     * @param userName the userName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract withUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Get the submittedDateTime value.
     *
     * @return the submittedDateTime value
     */
    public String submittedDateTime() {
        return this.submittedDateTime;
    }

    /**
     * Set the submittedDateTime value.
     *
     * @param submittedDateTime the submittedDateTime value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeContract withSubmittedDateTime(String submittedDateTime) {
        this.submittedDateTime = submittedDateTime;
        return this;
    }

}
