/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile {
    /**
     * The reviewerName property.
     */
    @JsonProperty(value = "reviewerName")
    private String reviewerName;

    /**
     * The reviewerRank property.
     */
    @JsonProperty(value = "reviewerRank")
    private Long reviewerRank;

    /**
     * The percentageThoughtful property.
     */
    @JsonProperty(value = "percentageThoughtful")
    private Double percentageThoughtful;

    /**
     * The followed property.
     */
    @JsonProperty(value = "followed")
    private Boolean followed;

    /**
     * Get the reviewerName value.
     *
     * @return the reviewerName value
     */
    public String reviewerName() {
        return this.reviewerName;
    }

    /**
     * Set the reviewerName value.
     *
     * @param reviewerName the reviewerName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile withReviewerName(String reviewerName) {
        this.reviewerName = reviewerName;
        return this;
    }

    /**
     * Get the reviewerRank value.
     *
     * @return the reviewerRank value
     */
    public Long reviewerRank() {
        return this.reviewerRank;
    }

    /**
     * Set the reviewerRank value.
     *
     * @param reviewerRank the reviewerRank value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile withReviewerRank(Long reviewerRank) {
        this.reviewerRank = reviewerRank;
        return this;
    }

    /**
     * Get the percentageThoughtful value.
     *
     * @return the percentageThoughtful value
     */
    public Double percentageThoughtful() {
        return this.percentageThoughtful;
    }

    /**
     * Set the percentageThoughtful value.
     *
     * @param percentageThoughtful the percentageThoughtful value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile withPercentageThoughtful(Double percentageThoughtful) {
        this.percentageThoughtful = percentageThoughtful;
        return this;
    }

    /**
     * Get the followed value.
     *
     * @return the followed value
     */
    public Boolean followed() {
        return this.followed;
    }

    /**
     * Set the followed value.
     *
     * @param followed the followed value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ReviewerProfile withFollowed(Boolean followed) {
        this.followed = followed;
        return this;
    }

}
