/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract {
    /**
     * The objectId property.
     */
    @JsonProperty(value = "objectId")
    private String objectId;

    /**
     * The likeCount property.
     */
    @JsonProperty(value = "likeCount")
    private Integer likeCount;

    /**
     * Get the objectId value.
     *
     * @return the objectId value
     */
    public String objectId() {
        return this.objectId;
    }

    /**
     * Set the objectId value.
     *
     * @param objectId the objectId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract withObjectId(String objectId) {
        this.objectId = objectId;
        return this;
    }

    /**
     * Get the likeCount value.
     *
     * @return the likeCount value
     */
    public Integer likeCount() {
        return this.likeCount;
    }

    /**
     * Set the likeCount value.
     *
     * @param likeCount the likeCount value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract withLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
        return this;
    }

}
