/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract {
    /**
     * The minutesPlayed property.
     */
    @JsonProperty(value = "minutesPlayed")
    private Integer minutesPlayed;

    /**
     * The verifiedPurchase property.
     */
    @JsonProperty(value = "verifiedPurchase")
    private Boolean verifiedPurchase;

    /**
     * Get the minutesPlayed value.
     *
     * @return the minutesPlayed value
     */
    public Integer minutesPlayed() {
        return this.minutesPlayed;
    }

    /**
     * Set the minutesPlayed value.
     *
     * @param minutesPlayed the minutesPlayed value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract withMinutesPlayed(Integer minutesPlayed) {
        this.minutesPlayed = minutesPlayed;
        return this;
    }

    /**
     * Get the verifiedPurchase value.
     *
     * @return the verifiedPurchase value
     */
    public Boolean verifiedPurchase() {
        return this.verifiedPurchase;
    }

    /**
     * Set the verifiedPurchase value.
     *
     * @param verifiedPurchase the verifiedPurchase value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UsageDataContract withVerifiedPurchase(Boolean verifiedPurchase) {
        this.verifiedPurchase = verifiedPurchase;
        return this;
    }

}
