/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkUserLikeSummaryContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkUserLikeSummaryContract {
    /**
     * The objectLikeStatus property.
     */
    @JsonProperty(value = "objectLikeStatus")
    private List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract> objectLikeStatus;

    /**
     * Get the objectLikeStatus value.
     *
     * @return the objectLikeStatus value
     */
    public List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract> objectLikeStatus() {
        return this.objectLikeStatus;
    }

    /**
     * Set the objectLikeStatus value.
     *
     * @param objectLikeStatus the objectLikeStatus value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkUserLikeSummaryContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkUserLikeSummaryContract withObjectLikeStatus(List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1UserLikeSummaryContract> objectLikeStatus) {
        this.objectLikeStatus = objectLikeStatus;
        return this;
    }

}
