/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitCommentContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitCommentContract {
    /**
     * The commentText property.
     */
    @JsonProperty(value = "commentText")
    private String commentText;

    /**
     * The authorName property.
     */
    @JsonProperty(value = "authorName")
    private String authorName;

    /**
     * Get the commentText value.
     *
     * @return the commentText value
     */
    public String commentText() {
        return this.commentText;
    }

    /**
     * Set the commentText value.
     *
     * @param commentText the commentText value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitCommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitCommentContract withCommentText(String commentText) {
        this.commentText = commentText;
        return this;
    }

    /**
     * Get the authorName value.
     *
     * @return the authorName value
     */
    public String authorName() {
        return this.authorName;
    }

    /**
     * Set the authorName value.
     *
     * @param authorName the authorName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitCommentContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitCommentContract withAuthorName(String authorName) {
        this.authorName = authorName;
        return this;
    }

}
