/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract {
    /**
     * The deviceFamily property.
     */
    @JsonProperty(value = "deviceFamily")
    private String deviceFamily;

    /**
     * The userName property.
     */
    @JsonProperty(value = "userName")
    private String userName;

    /**
     * The title property.
     */
    @JsonProperty(value = "title")
    private String title;

    /**
     * The reviewText property.
     */
    @JsonProperty(value = "reviewText")
    private String reviewText;

    /**
     * The rating property.
     */
    @JsonProperty(value = "rating")
    private Integer rating;

    /**
     * The isProductTrial property.
     */
    @JsonProperty(value = "isProductTrial")
    private Boolean isProductTrial;

    /**
     * The productFamily property.
     */
    @JsonProperty(value = "productFamily")
    private String productFamily;

    /**
     * The isAppInstalled property.
     */
    @JsonProperty(value = "isAppInstalled")
    private Boolean isAppInstalled;

    /**
     * The packageFullName property.
     */
    @JsonProperty(value = "packageFullName")
    private String packageFullName;

    /**
     * The xType property.
     */
    @JsonProperty(value = "xType")
    private String xType;

    /**
     * The deviceId property.
     */
    @JsonProperty(value = "deviceId")
    private String deviceId;

    /**
     * The osVersion property.
     */
    @JsonProperty(value = "osVersion")
    private String osVersion;

    /**
     * Get the deviceFamily value.
     *
     * @return the deviceFamily value
     */
    public String deviceFamily() {
        return this.deviceFamily;
    }

    /**
     * Set the deviceFamily value.
     *
     * @param deviceFamily the deviceFamily value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withDeviceFamily(String deviceFamily) {
        this.deviceFamily = deviceFamily;
        return this;
    }

    /**
     * Get the userName value.
     *
     * @return the userName value
     */
    public String userName() {
        return this.userName;
    }

    /**
     * Set the userName value.
     *
     * @param userName the userName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Get the title value.
     *
     * @return the title value
     */
    public String title() {
        return this.title;
    }

    /**
     * Set the title value.
     *
     * @param title the title value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get the reviewText value.
     *
     * @return the reviewText value
     */
    public String reviewText() {
        return this.reviewText;
    }

    /**
     * Set the reviewText value.
     *
     * @param reviewText the reviewText value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withReviewText(String reviewText) {
        this.reviewText = reviewText;
        return this;
    }

    /**
     * Get the rating value.
     *
     * @return the rating value
     */
    public Integer rating() {
        return this.rating;
    }

    /**
     * Set the rating value.
     *
     * @param rating the rating value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    /**
     * Get the isProductTrial value.
     *
     * @return the isProductTrial value
     */
    public Boolean isProductTrial() {
        return this.isProductTrial;
    }

    /**
     * Set the isProductTrial value.
     *
     * @param isProductTrial the isProductTrial value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withIsProductTrial(Boolean isProductTrial) {
        this.isProductTrial = isProductTrial;
        return this;
    }

    /**
     * Get the productFamily value.
     *
     * @return the productFamily value
     */
    public String productFamily() {
        return this.productFamily;
    }

    /**
     * Set the productFamily value.
     *
     * @param productFamily the productFamily value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withProductFamily(String productFamily) {
        this.productFamily = productFamily;
        return this;
    }

    /**
     * Get the isAppInstalled value.
     *
     * @return the isAppInstalled value
     */
    public Boolean isAppInstalled() {
        return this.isAppInstalled;
    }

    /**
     * Set the isAppInstalled value.
     *
     * @param isAppInstalled the isAppInstalled value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withIsAppInstalled(Boolean isAppInstalled) {
        this.isAppInstalled = isAppInstalled;
        return this;
    }

    /**
     * Get the packageFullName value.
     *
     * @return the packageFullName value
     */
    public String packageFullName() {
        return this.packageFullName;
    }

    /**
     * Set the packageFullName value.
     *
     * @param packageFullName the packageFullName value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withPackageFullName(String packageFullName) {
        this.packageFullName = packageFullName;
        return this;
    }

    /**
     * Get the xType value.
     *
     * @return the xType value
     */
    public String xType() {
        return this.xType;
    }

    /**
     * Set the xType value.
     *
     * @param xType the xType value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withXType(String xType) {
        this.xType = xType;
        return this;
    }

    /**
     * Get the deviceId value.
     *
     * @return the deviceId value
     */
    public String deviceId() {
        return this.deviceId;
    }

    /**
     * Set the deviceId value.
     *
     * @param deviceId the deviceId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withDeviceId(String deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get the osVersion value.
     *
     * @return the osVersion value
     */
    public String osVersion() {
        return this.osVersion;
    }

    /**
     * Set the osVersion value.
     *
     * @param osVersion the osVersion value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewContract withOsVersion(String osVersion) {
        this.osVersion = osVersion;
        return this;
    }

}
