/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract {
    /**
     * The reaction property.
     */
    @JsonProperty(value = "reaction")
    private Integer reaction;

    /**
     * The impressionId property.
     */
    @JsonProperty(value = "impressionId")
    private String impressionId;

    /**
     * The objectType property.
     */
    @JsonProperty(value = "objectType")
    private String objectType;

    /**
     * Get the reaction value.
     *
     * @return the reaction value
     */
    public Integer reaction() {
        return this.reaction;
    }

    /**
     * Set the reaction value.
     *
     * @param reaction the reaction value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract withReaction(Integer reaction) {
        this.reaction = reaction;
        return this;
    }

    /**
     * Get the impressionId value.
     *
     * @return the impressionId value
     */
    public String impressionId() {
        return this.impressionId;
    }

    /**
     * Set the impressionId value.
     *
     * @param impressionId the impressionId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract withImpressionId(String impressionId) {
        this.impressionId = impressionId;
        return this;
    }

    /**
     * Get the objectType value.
     *
     * @return the objectType value
     */
    public String objectType() {
        return this.objectType;
    }

    /**
     * Set the objectType value.
     *
     * @param objectType the objectType value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReactionContract withObjectType(String objectType) {
        this.objectType = objectType;
        return this;
    }

}
