/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract
 * model.
 */
@JsonIgnoreProperties(ignoreUnknown=true)
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract {
    /**
     * The continuationToken property.
     */
    @JsonProperty(value = "continuationToken")
    private String continuationToken;

    /**
     * The totalItems property.
     */
    @JsonProperty(value = "totalItems")
    private Integer totalItems;

    /**
     * Get the continuationToken value.
     *
     * @return the continuationToken value
     */
    public String continuationToken() {
        return this.continuationToken;
    }

    /**
     * Set the continuationToken value.
     *
     * @param continuationToken the continuationToken value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract withContinuationToken(String continuationToken) {
        this.continuationToken = continuationToken;
        return this;
    }

    /**
     * Get the totalItems value.
     *
     * @return the totalItems value
     */
    public Integer totalItems() {
        return this.totalItems;
    }

    /**
     * Set the totalItems value.
     *
     * @param totalItems the totalItems value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1PagingInfoContract withTotalItems(Integer totalItems) {
        this.totalItems = totalItems;
        return this;
    }

}
