/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract {
    /**
     * The isHelpful property.
     */
    @JsonProperty(value = "isHelpful")
    private Boolean isHelpful;

    /**
     * The deviceId property.
     */
    @JsonProperty(value = "deviceId")
    private String deviceId;

    /**
     * The osVersion property.
     */
    @JsonProperty(value = "osVersion")
    private String osVersion;

    /**
     * Get the isHelpful value.
     *
     * @return the isHelpful value
     */
    public Boolean isHelpful() {
        return this.isHelpful;
    }

    /**
     * Set the isHelpful value.
     *
     * @param isHelpful the isHelpful value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract withIsHelpful(Boolean isHelpful) {
        this.isHelpful = isHelpful;
        return this;
    }

    /**
     * Get the deviceId value.
     *
     * @return the deviceId value
     */
    public String deviceId() {
        return this.deviceId;
    }

    /**
     * Set the deviceId value.
     *
     * @param deviceId the deviceId value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract withDeviceId(String deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    /**
     * Get the osVersion value.
     *
     * @return the osVersion value
     */
    public String osVersion() {
        return this.osVersion;
    }

    /**
     * Set the osVersion value.
     *
     * @param osVersion the osVersion value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitHelpfulnessVoteContract withOsVersion(String osVersion) {
        this.osVersion = osVersion;
        return this;
    }

}
