/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewsContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewsContract {
    /**
     * The reviews property.
     */
    @JsonProperty(value = "reviews")
    private List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitBulkReviewItemContract> reviews;

    /**
     * Get the reviews value.
     *
     * @return the reviews value
     */
    public List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitBulkReviewItemContract> reviews() {
        return this.reviews;
    }

    /**
     * Set the reviews value.
     *
     * @param reviews the reviews value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewsContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitReviewsContract withReviews(List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1SubmitBulkReviewItemContract> reviews) {
        this.reviews = reviews;
        return this;
    }

}
