/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkObjectLikeSummaryContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkObjectLikeSummaryContract {
    /**
     * The objectLikeCounts property.
     */
    @JsonProperty(value = "objectLikeCounts")
    private List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract> objectLikeCounts;

    /**
     * Get the objectLikeCounts value.
     *
     * @return the objectLikeCounts value
     */
    public List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract> objectLikeCounts() {
        return this.objectLikeCounts;
    }

    /**
     * Set the objectLikeCounts value.
     *
     * @param objectLikeCounts the objectLikeCounts value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkObjectLikeSummaryContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkObjectLikeSummaryContract withObjectLikeCounts(List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1ObjectLikeSummaryContract> objectLikeCounts) {
        this.objectLikeCounts = objectLikeCounts;
        return this;
    }

}
