/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.ratingsedgefd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkAverageRatingsContract
 * model.
 */
public class MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkAverageRatingsContract {
    /**
     * The averageRatings property.
     */
    @JsonProperty(value = "averageRatings")
    private List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1AverageRatingContract> averageRatings;

    /**
     * Get the averageRatings value.
     *
     * @return the averageRatings value
     */
    public List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1AverageRatingContract> averageRatings() {
        return this.averageRatings;
    }

    /**
     * Set the averageRatings value.
     *
     * @param averageRatings the averageRatings value to set
     * @return the MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkAverageRatingsContract object itself.
     */
    public MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1BulkAverageRatingsContract withAverageRatings(List<MicrosoftMarketplaceStorefrontRatingsRatingsEdgeContractsV1AverageRatingContract> averageRatings) {
        this.averageRatings = averageRatings;
        return this;
    }

}
