/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingResponseV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingResponseV7 {
    /**
     * The pricingParameters property.
     */
    @JsonProperty(value = "pricingParameters")
    private MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingParametersV7 pricingParameters;

    /**
     * The products property.
     */
    @JsonProperty(value = "products", access = JsonProperty.Access.WRITE_ONLY)
    private List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7> products;

    /**
     * The productsNotFound property.
     */
    @JsonProperty(value = "productsNotFound", access = JsonProperty.Access.WRITE_ONLY)
    private Map<String, String> productsNotFound;

    /**
     * Get the pricingParameters value.
     *
     * @return the pricingParameters value
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingParametersV7 pricingParameters() {
        return this.pricingParameters;
    }

    /**
     * Set the pricingParameters value.
     *
     * @param pricingParameters the pricingParameters value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingResponseV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingResponseV7 withPricingParameters(MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingParametersV7 pricingParameters) {
        this.pricingParameters = pricingParameters;
        return this;
    }

    /**
     * Get the products value.
     *
     * @return the products value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7> products() {
        return this.products;
    }

    /**
     * Get the productsNotFound value.
     *
     * @return the productsNotFound value
     */
    public Map<String, String> productsNotFound() {
        return this.productsNotFound;
    }

}
