/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 {
    /**
     * The currencyCode property.
     */
    @JsonProperty(value = "currencyCode")
    private String currencyCode;

    /**
     * The modifiedUnitPrice property.
     */
    @JsonProperty(value = "modifiedUnitPrice")
    private Double modifiedUnitPrice;

    /**
     * The totalPrice property.
     */
    @JsonProperty(value = "totalPrice")
    private Double totalPrice;

    /**
     * The unitPrice property.
     */
    @JsonProperty(value = "unitPrice")
    private Double unitPrice;

    /**
     * Get the currencyCode value.
     *
     * @return the currencyCode value
     */
    public String currencyCode() {
        return this.currencyCode;
    }

    /**
     * Set the currencyCode value.
     *
     * @param currencyCode the currencyCode value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 withCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
        return this;
    }

    /**
     * Get the modifiedUnitPrice value.
     *
     * @return the modifiedUnitPrice value
     */
    public Double modifiedUnitPrice() {
        return this.modifiedUnitPrice;
    }

    /**
     * Set the modifiedUnitPrice value.
     *
     * @param modifiedUnitPrice the modifiedUnitPrice value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 withModifiedUnitPrice(Double modifiedUnitPrice) {
        this.modifiedUnitPrice = modifiedUnitPrice;
        return this;
    }

    /**
     * Get the totalPrice value.
     *
     * @return the totalPrice value
     */
    public Double totalPrice() {
        return this.totalPrice;
    }

    /**
     * Set the totalPrice value.
     *
     * @param totalPrice the totalPrice value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 withTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
        return this;
    }

    /**
     * Get the unitPrice value.
     *
     * @return the unitPrice value
     */
    public Double unitPrice() {
        return this.unitPrice;
    }

    /**
     * Set the unitPrice value.
     *
     * @param unitPrice the unitPrice value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 withUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
        return this;
    }

}
