/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The type property.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * The title property.
     */
    @JsonProperty(value = "title")
    private String title;

    /**
     * The avgRating property.
     */
    @JsonProperty(value = "avgRating")
    private Double avgRating;

    /**
     * The price property.
     */
    @JsonProperty(value = "price")
    private Double price;

    /**
     * The icon property.
     */
    @JsonProperty(value = "icon")
    private String icon;

    /**
     * The ratings property.
     */
    @JsonProperty(value = "ratings")
    private Integer ratings;

    /**
     * The backgroundColor property.
     */
    @JsonProperty(value = "backgroundColor")
    private String backgroundColor;

    /**
     * The height property.
     */
    @JsonProperty(value = "height")
    private Integer height;

    /**
     * The width property.
     */
    @JsonProperty(value = "width")
    private Integer width;

    /**
     * The imageType property.
     */
    @JsonProperty(value = "imageType")
    private String imageType;

    /**
     * The platformProperties property.
     */
    @JsonProperty(value = "platformProperties", access = JsonProperty.Access.WRITE_ONLY)
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty> platformProperties;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the title value.
     *
     * @return the title value
     */
    public String title() {
        return this.title;
    }

    /**
     * Set the title value.
     *
     * @param title the title value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get the avgRating value.
     *
     * @return the avgRating value
     */
    public Double avgRating() {
        return this.avgRating;
    }

    /**
     * Set the avgRating value.
     *
     * @param avgRating the avgRating value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withAvgRating(Double avgRating) {
        this.avgRating = avgRating;
        return this;
    }

    /**
     * Get the price value.
     *
     * @return the price value
     */
    public Double price() {
        return this.price;
    }

    /**
     * Set the price value.
     *
     * @param price the price value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withPrice(Double price) {
        this.price = price;
        return this;
    }

    /**
     * Get the icon value.
     *
     * @return the icon value
     */
    public String icon() {
        return this.icon;
    }

    /**
     * Set the icon value.
     *
     * @param icon the icon value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withIcon(String icon) {
        this.icon = icon;
        return this;
    }

    /**
     * Get the ratings value.
     *
     * @return the ratings value
     */
    public Integer ratings() {
        return this.ratings;
    }

    /**
     * Set the ratings value.
     *
     * @param ratings the ratings value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withRatings(Integer ratings) {
        this.ratings = ratings;
        return this;
    }

    /**
     * Get the backgroundColor value.
     *
     * @return the backgroundColor value
     */
    public String backgroundColor() {
        return this.backgroundColor;
    }

    /**
     * Set the backgroundColor value.
     *
     * @param backgroundColor the backgroundColor value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
        return this;
    }

    /**
     * Get the height value.
     *
     * @return the height value
     */
    public Integer height() {
        return this.height;
    }

    /**
     * Set the height value.
     *
     * @param height the height value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withHeight(Integer height) {
        this.height = height;
        return this;
    }

    /**
     * Get the width value.
     *
     * @return the width value
     */
    public Integer width() {
        return this.width;
    }

    /**
     * Set the width value.
     *
     * @param width the width value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withWidth(Integer width) {
        this.width = width;
        return this;
    }

    /**
     * Get the imageType value.
     *
     * @return the imageType value
     */
    public String imageType() {
        return this.imageType;
    }

    /**
     * Set the imageType value.
     *
     * @param imageType the imageType value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct withImageType(String imageType) {
        this.imageType = imageType;
        return this;
    }

    /**
     * Get the platformProperties value.
     *
     * @return the platformProperties value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty> platformProperties() {
        return this.platformProperties;
    }

}
