/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7OrderHistoryV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7OrderHistoryV7 {
    /**
     * The pricingGroupId property.
     */
    @JsonProperty(value = "pricingGroupId")
    private String pricingGroupId;

    /**
     * The volume property.
     */
    @JsonProperty(value = "volume")
    private Long volume;

    /**
     * Get the pricingGroupId value.
     *
     * @return the pricingGroupId value
     */
    public String pricingGroupId() {
        return this.pricingGroupId;
    }

    /**
     * Set the pricingGroupId value.
     *
     * @param pricingGroupId the pricingGroupId value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7OrderHistoryV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7OrderHistoryV7 withPricingGroupId(String pricingGroupId) {
        this.pricingGroupId = pricingGroupId;
        return this;
    }

    /**
     * Get the volume value.
     *
     * @return the volume value
     */
    public Long volume() {
        return this.volume;
    }

    /**
     * Set the volume value.
     *
     * @param volume the volume value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7OrderHistoryV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7OrderHistoryV7 withVolume(Long volume) {
        this.volume = volume;
        return this;
    }

}
