/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty {
    /**
     * The platformName property.
     */
    @JsonProperty(value = "platformName")
    private String platformName;

    /**
     * The titleOverride property.
     */
    @JsonProperty(value = "titleOverride")
    private String titleOverride;

    /**
     * Get the platformName value.
     *
     * @return the platformName value
     */
    public String platformName() {
        return this.platformName;
    }

    /**
     * Set the platformName value.
     *
     * @param platformName the platformName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty withPlatformName(String platformName) {
        this.platformName = platformName;
        return this;
    }

    /**
     * Get the titleOverride value.
     *
     * @return the titleOverride value
     */
    public String titleOverride() {
        return this.titleOverride;
    }

    /**
     * Set the titleOverride value.
     *
     * @param titleOverride the titleOverride value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultPlatformProperty withTitleOverride(String titleOverride) {
        this.titleOverride = titleOverride;
        return this;
    }

}
