/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7 {
    /**
     * The bigId property.
     */
    @JsonProperty(value = "bigId")
    private String bigId;

    /**
     * The currencyCode property.
     */
    @JsonProperty(value = "currencyCode")
    private String currencyCode;

    /**
     * The unitPrice property.
     */
    @JsonProperty(value = "unitPrice")
    private Double unitPrice;

    /**
     * The pricingRules property.
     */
    @JsonProperty(value = "pricingRules", access = JsonProperty.Access.WRITE_ONLY)
    private List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceScheduleRuleV7> pricingRules;

    /**
     * Get the bigId value.
     *
     * @return the bigId value
     */
    public String bigId() {
        return this.bigId;
    }

    /**
     * Set the bigId value.
     *
     * @param bigId the bigId value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7 withBigId(String bigId) {
        this.bigId = bigId;
        return this;
    }

    /**
     * Get the currencyCode value.
     *
     * @return the currencyCode value
     */
    public String currencyCode() {
        return this.currencyCode;
    }

    /**
     * Set the currencyCode value.
     *
     * @param currencyCode the currencyCode value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7 withCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
        return this;
    }

    /**
     * Get the unitPrice value.
     *
     * @return the unitPrice value
     */
    public Double unitPrice() {
        return this.unitPrice;
    }

    /**
     * Set the unitPrice value.
     *
     * @param unitPrice the unitPrice value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7 withUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
        return this;
    }

    /**
     * Get the pricingRules value.
     *
     * @return the pricingRules value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceScheduleRuleV7> pricingRules() {
        return this.pricingRules;
    }

}
