/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The localizedString property.
     */
    @JsonProperty(value = "localizedString")
    private String localizedString;

    /**
     * The hasChildren property.
     */
    @JsonProperty(value = "hasChildren")
    private Boolean hasChildren;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the localizedString value.
     *
     * @return the localizedString value
     */
    public String localizedString() {
        return this.localizedString;
    }

    /**
     * Set the localizedString value.
     *
     * @param localizedString the localizedString value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract withLocalizedString(String localizedString) {
        this.localizedString = localizedString;
        return this;
    }

    /**
     * Get the hasChildren value.
     *
     * @return the hasChildren value
     */
    public Boolean hasChildren() {
        return this.hasChildren;
    }

    /**
     * Set the hasChildren value.
     *
     * @param hasChildren the hasChildren value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract withHasChildren(Boolean hasChildren) {
        this.hasChildren = hasChildren;
        return this;
    }

}
