/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6BulkProductDetailsResponseContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6BulkProductDetailsResponseContract {
    /**
     * The products property.
     */
    @JsonProperty(value = "products")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetails> products;

    /**
     * Get the products value.
     *
     * @return the products value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetails> products() {
        return this.products;
    }

    /**
     * Set the products value.
     *
     * @param products the products value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6BulkProductDetailsResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6BulkProductDetailsResponseContract withProducts(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetails> products) {
        this.products = products;
        return this;
    }

}
