/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract {
    /**
     * The catalogId property.
     */
    @JsonProperty(value = "catalogId")
    private String catalogId;

    /**
     * The catalogType property.
     */
    @JsonProperty(value = "catalogType")
    private String catalogType;

    /**
     * The catalogName property.
     */
    @JsonProperty(value = "catalogName")
    private String catalogName;

    /**
     * The catalogTitle property.
     */
    @JsonProperty(value = "catalogTitle")
    private String catalogTitle;

    /**
     * Get the catalogId value.
     *
     * @return the catalogId value
     */
    public String catalogId() {
        return this.catalogId;
    }

    /**
     * Set the catalogId value.
     *
     * @param catalogId the catalogId value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract withCatalogId(String catalogId) {
        this.catalogId = catalogId;
        return this;
    }

    /**
     * Get the catalogType value.
     *
     * @return the catalogType value
     */
    public String catalogType() {
        return this.catalogType;
    }

    /**
     * Set the catalogType value.
     *
     * @param catalogType the catalogType value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract withCatalogType(String catalogType) {
        this.catalogType = catalogType;
        return this;
    }

    /**
     * Get the catalogName value.
     *
     * @return the catalogName value
     */
    public String catalogName() {
        return this.catalogName;
    }

    /**
     * Set the catalogName value.
     *
     * @param catalogName the catalogName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract withCatalogName(String catalogName) {
        this.catalogName = catalogName;
        return this;
    }

    /**
     * Get the catalogTitle value.
     *
     * @return the catalogTitle value
     */
    public String catalogTitle() {
        return this.catalogTitle;
    }

    /**
     * Set the catalogTitle value.
     *
     * @param catalogTitle the catalogTitle value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6CatalogManifestResponseContract withCatalogTitle(String catalogTitle) {
        this.catalogTitle = catalogTitle;
        return this;
    }

}
