/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceSchedulesResponseV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceSchedulesResponseV7 {
    /**
     * The products property.
     */
    @JsonProperty(value = "products", access = JsonProperty.Access.WRITE_ONLY)
    private List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7> products;

    /**
     * The productsNotFound property.
     */
    @JsonProperty(value = "productsNotFound", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> productsNotFound;

    /**
     * Get the products value.
     *
     * @return the products value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPriceScheduleV7> products() {
        return this.products;
    }

    /**
     * Get the productsNotFound value.
     *
     * @return the productsNotFound value
     */
    public List<String> productsNotFound() {
        return this.productsNotFound;
    }

}
