/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingsContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingsContract {
    /**
     * The ratingBoards property.
     */
    @JsonProperty(value = "ratingBoards")
    private Map<String, MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoard> ratingBoards;

    /**
     * Get the ratingBoards value.
     *
     * @return the ratingBoards value
     */
    public Map<String, MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoard> ratingBoards() {
        return this.ratingBoards;
    }

    /**
     * Set the ratingBoards value.
     *
     * @param ratingBoards the ratingBoards value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingsContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingsContract withRatingBoards(Map<String, MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoard> ratingBoards) {
        this.ratingBoards = ratingBoards;
        return this;
    }

}
