/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7 {
    /**
     * The bigId property.
     */
    @JsonProperty(value = "bigId")
    private String bigId;

    /**
     * The price property.
     */
    @JsonProperty(value = "price")
    private MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 price;

    /**
     * The pricingContext property.
     */
    @JsonProperty(value = "pricingContext")
    private MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingContextV7 pricingContext;

    /**
     * Get the bigId value.
     *
     * @return the bigId value
     */
    public String bigId() {
        return this.bigId;
    }

    /**
     * Set the bigId value.
     *
     * @param bigId the bigId value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7 withBigId(String bigId) {
        this.bigId = bigId;
        return this;
    }

    /**
     * Get the price value.
     *
     * @return the price value
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 price() {
        return this.price;
    }

    /**
     * Set the price value.
     *
     * @param price the price value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7 withPrice(MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PriceV7 price) {
        this.price = price;
        return this;
    }

    /**
     * Get the pricingContext value.
     *
     * @return the pricingContext value
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingContextV7 pricingContext() {
        return this.pricingContext;
    }

    /**
     * Set the pricingContext value.
     *
     * @param pricingContext the pricingContext value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingProductV7 withPricingContext(MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingContextV7 pricingContext) {
        this.pricingContext = pricingContext;
        return this;
    }

}
