/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer {
    /**
     * The disclaimer property.
     */
    @JsonProperty(value = "disclaimer")
    private String disclaimer;

    /**
     * The logoUrl property.
     */
    @JsonProperty(value = "logoUrl")
    private String logoUrl;

    /**
     * The key property.
     */
    @JsonProperty(value = "key")
    private String key;

    /**
     * Get the disclaimer value.
     *
     * @return the disclaimer value
     */
    public String disclaimer() {
        return this.disclaimer;
    }

    /**
     * Set the disclaimer value.
     *
     * @param disclaimer the disclaimer value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer withDisclaimer(String disclaimer) {
        this.disclaimer = disclaimer;
        return this;
    }

    /**
     * Get the logoUrl value.
     *
     * @return the logoUrl value
     */
    public String logoUrl() {
        return this.logoUrl;
    }

    /**
     * Set the logoUrl value.
     *
     * @param logoUrl the logoUrl value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer withLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
        return this;
    }

    /**
     * Get the key value.
     *
     * @return the key value
     */
    public String key() {
        return this.key;
    }

    /**
     * Set the key value.
     *
     * @param key the key value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer withKey(String key) {
        this.key = key;
        return this;
    }

}
