/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract {
    /**
     * The productFamilyName property.
     */
    @JsonProperty(value = "productFamilyName")
    private String productFamilyName;

    /**
     * The products property.
     */
    @JsonProperty(value = "products")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct> products;

    /**
     * The queries property.
     */
    @JsonProperty(value = "queries")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultQuery> queries;

    /**
     * Get the productFamilyName value.
     *
     * @return the productFamilyName value
     */
    public String productFamilyName() {
        return this.productFamilyName;
    }

    /**
     * Set the productFamilyName value.
     *
     * @param productFamilyName the productFamilyName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract withProductFamilyName(String productFamilyName) {
        this.productFamilyName = productFamilyName;
        return this;
    }

    /**
     * Get the products value.
     *
     * @return the products value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct> products() {
        return this.products;
    }

    /**
     * Set the products value.
     *
     * @param products the products value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract withProducts(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultProduct> products) {
        this.products = products;
        return this;
    }

    /**
     * Get the queries value.
     *
     * @return the queries value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultQuery> queries() {
        return this.queries;
    }

    /**
     * Set the queries value.
     *
     * @param queries the queries value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultResponseContract withQueries(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultQuery> queries) {
        this.queries = queries;
        return this;
    }

}
