/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultQuery
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultQuery {
    /**
     * The q property.
     */
    @JsonProperty(value = "q")
    private String q;

    /**
     * Get the q value.
     *
     * @return the q value
     */
    public String q() {
        return this.q;
    }

    /**
     * Set the q value.
     *
     * @param q the q value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultQuery object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6AutosuggestResultQuery withQ(String q) {
        this.q = q;
        return this;
    }

}
