/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 {
    /**
     * The rangeBegin property.
     */
    @JsonProperty(value = "rangeBegin")
    private Long rangeBegin;

    /**
     * The rangeEnd property.
     */
    @JsonProperty(value = "rangeEnd")
    private Long rangeEnd;

    /**
     * Get the rangeBegin value.
     *
     * @return the rangeBegin value
     */
    public Long rangeBegin() {
        return this.rangeBegin;
    }

    /**
     * Set the rangeBegin value.
     *
     * @param rangeBegin the rangeBegin value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 withRangeBegin(Long rangeBegin) {
        this.rangeBegin = rangeBegin;
        return this;
    }

    /**
     * Get the rangeEnd value.
     *
     * @return the rangeEnd value
     */
    public Long rangeEnd() {
        return this.rangeEnd;
    }

    /**
     * Set the rangeEnd value.
     *
     * @param rangeEnd the rangeEnd value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 withRangeEnd(Long rangeEnd) {
        this.rangeEnd = rangeEnd;
        return this;
    }

}
