/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract {
    /**
     * The domainDataVersion property.
     */
    @JsonProperty(value = "domainDataVersion")
    private Integer domainDataVersion;

    /**
     * The market property.
     */
    @JsonProperty(value = "market")
    private String market;

    /**
     * The language property.
     */
    @JsonProperty(value = "language")
    private String language;

    /**
     * The keys property.
     */
    @JsonProperty(value = "keys")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract> keys;

    /**
     * Get the domainDataVersion value.
     *
     * @return the domainDataVersion value
     */
    public Integer domainDataVersion() {
        return this.domainDataVersion;
    }

    /**
     * Set the domainDataVersion value.
     *
     * @param domainDataVersion the domainDataVersion value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract withDomainDataVersion(Integer domainDataVersion) {
        this.domainDataVersion = domainDataVersion;
        return this;
    }

    /**
     * Get the market value.
     *
     * @return the market value
     */
    public String market() {
        return this.market;
    }

    /**
     * Set the market value.
     *
     * @param market the market value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract withMarket(String market) {
        this.market = market;
        return this;
    }

    /**
     * Get the language value.
     *
     * @return the language value
     */
    public String language() {
        return this.language;
    }

    /**
     * Set the language value.
     *
     * @param language the language value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract withLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get the keys value.
     *
     * @return the keys value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract> keys() {
        return this.keys;
    }

    /**
     * Set the keys value.
     *
     * @param keys the keys value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeContract withKeys(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataKeyContract> keys) {
        this.keys = keys;
        return this;
    }

}
