/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7 {
    /**
     * The key property.
     */
    @JsonProperty(value = "key")
    private String key;

    /**
     * The type property.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Get the key value.
     *
     * @return the key value
     */
    public String key() {
        return this.key;
    }

    /**
     * Set the key value.
     *
     * @param key the key value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7 withKey(String key) {
        this.key = key;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7 withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7 withValue(String value) {
        this.value = value;
        return this;
    }

}
