/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataSetContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataSetContract {
    /**
     * The domain property.
     */
    @JsonProperty(value = "domain")
    private String domain;

    /**
     * The types property.
     */
    @JsonProperty(value = "types")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeDescriptor> types;

    /**
     * Get the domain value.
     *
     * @return the domain value
     */
    public String domain() {
        return this.domain;
    }

    /**
     * Set the domain value.
     *
     * @param domain the domain value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataSetContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataSetContract withDomain(String domain) {
        this.domain = domain;
        return this;
    }

    /**
     * Get the types value.
     *
     * @return the types value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeDescriptor> types() {
        return this.types;
    }

    /**
     * Set the types value.
     *
     * @param types the types value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataSetContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataSetContract withTypes(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6DomainDataTypeDescriptor> types) {
        this.types = types;
        return this;
    }

}
