/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties {
    /**
     * The market property.
     */
    @JsonProperty(value = "market")
    private String market;

    /**
     * The excludedDomains property.
     */
    @JsonProperty(value = "excludedDomains")
    private List<String> excludedDomains;

    /**
     * The restrictMetadata property.
     */
    @JsonProperty(value = "restrictMetadata")
    private Boolean restrictMetadata;

    /**
     * The restrictPurchase property.
     */
    @JsonProperty(value = "restrictPurchase")
    private Boolean restrictPurchase;

    /**
     * Get the market value.
     *
     * @return the market value
     */
    public String market() {
        return this.market;
    }

    /**
     * Set the market value.
     *
     * @param market the market value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties withMarket(String market) {
        this.market = market;
        return this;
    }

    /**
     * Get the excludedDomains value.
     *
     * @return the excludedDomains value
     */
    public List<String> excludedDomains() {
        return this.excludedDomains;
    }

    /**
     * Set the excludedDomains value.
     *
     * @param excludedDomains the excludedDomains value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties withExcludedDomains(List<String> excludedDomains) {
        this.excludedDomains = excludedDomains;
        return this;
    }

    /**
     * Get the restrictMetadata value.
     *
     * @return the restrictMetadata value
     */
    public Boolean restrictMetadata() {
        return this.restrictMetadata;
    }

    /**
     * Set the restrictMetadata value.
     *
     * @param restrictMetadata the restrictMetadata value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties withRestrictMetadata(Boolean restrictMetadata) {
        this.restrictMetadata = restrictMetadata;
        return this;
    }

    /**
     * Get the restrictPurchase value.
     *
     * @return the restrictPurchase value
     */
    public Boolean restrictPurchase() {
        return this.restrictPurchase;
    }

    /**
     * Set the restrictPurchase value.
     *
     * @param restrictPurchase the restrictPurchase value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingMarketProperties withRestrictPurchase(Boolean restrictPurchase) {
        this.restrictPurchase = restrictPurchase;
        return this;
    }

}
