/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7 {
    /**
     * The affirmation property.
     */
    @JsonProperty(value = "affirmation")
    private String affirmation;

    /**
     * The affirmationParameters property.
     */
    @JsonProperty(value = "affirmationParameters", access = JsonProperty.Access.WRITE_ONLY)
    private List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7> affirmationParameters;

    /**
     * The pricingRuleId property.
     */
    @JsonProperty(value = "pricingRuleId")
    private String pricingRuleId;

    /**
     * Get the affirmation value.
     *
     * @return the affirmation value
     */
    public String affirmation() {
        return this.affirmation;
    }

    /**
     * Set the affirmation value.
     *
     * @param affirmation the affirmation value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7 withAffirmation(String affirmation) {
        this.affirmation = affirmation;
        return this;
    }

    /**
     * Get the affirmationParameters value.
     *
     * @return the affirmationParameters value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7AffirmationParameterV7> affirmationParameters() {
        return this.affirmationParameters;
    }

    /**
     * Get the pricingRuleId value.
     *
     * @return the pricingRuleId value
     */
    public String pricingRuleId() {
        return this.pricingRuleId;
    }

    /**
     * Set the pricingRuleId value.
     *
     * @param pricingRuleId the pricingRuleId value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7 withPricingRuleId(String pricingRuleId) {
        this.pricingRuleId = pricingRuleId;
        return this;
    }

}
