/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPricingParametersV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPricingParametersV7 {
    /**
     * The bigId property.
     */
    @JsonProperty(value = "bigId")
    private String bigId;

    /**
     * The parameters property.
     */
    @JsonProperty(value = "parameters", access = JsonProperty.Access.WRITE_ONLY)
    private Map<String, String> parameters;

    /**
     * Get the bigId value.
     *
     * @return the bigId value
     */
    public String bigId() {
        return this.bigId;
    }

    /**
     * Set the bigId value.
     *
     * @param bigId the bigId value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPricingParametersV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ProductPricingParametersV7 withBigId(String bigId) {
        this.bigId = bigId;
        return this;
    }

    /**
     * Get the parameters value.
     *
     * @return the parameters value
     */
    public Map<String, String> parameters() {
        return this.parameters;
    }

}
