/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties {
    /**
     * The language property.
     */
    @JsonProperty(value = "language")
    private String language;

    /**
     * The shortName property.
     */
    @JsonProperty(value = "shortName")
    private String shortName;

    /**
     * The longName property.
     */
    @JsonProperty(value = "longName")
    private String longName;

    /**
     * The url property.
     */
    @JsonProperty(value = "url")
    private String url;

    /**
     * The descriptors property.
     */
    @JsonProperty(value = "descriptors")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor> descriptors;

    /**
     * The disclaimers property.
     */
    @JsonProperty(value = "disclaimers")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer> disclaimers;

    /**
     * Get the language value.
     *
     * @return the language value
     */
    public String language() {
        return this.language;
    }

    /**
     * Set the language value.
     *
     * @param language the language value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties withLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get the shortName value.
     *
     * @return the shortName value
     */
    public String shortName() {
        return this.shortName;
    }

    /**
     * Set the shortName value.
     *
     * @param shortName the shortName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties withShortName(String shortName) {
        this.shortName = shortName;
        return this;
    }

    /**
     * Get the longName value.
     *
     * @return the longName value
     */
    public String longName() {
        return this.longName;
    }

    /**
     * Set the longName value.
     *
     * @param longName the longName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties withLongName(String longName) {
        this.longName = longName;
        return this;
    }

    /**
     * Get the url value.
     *
     * @return the url value
     */
    public String url() {
        return this.url;
    }

    /**
     * Set the url value.
     *
     * @param url the url value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get the descriptors value.
     *
     * @return the descriptors value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor> descriptors() {
        return this.descriptors;
    }

    /**
     * Set the descriptors value.
     *
     * @param descriptors the descriptors value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties withDescriptors(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor> descriptors) {
        this.descriptors = descriptors;
        return this;
    }

    /**
     * Get the disclaimers value.
     *
     * @return the disclaimers value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer> disclaimers() {
        return this.disclaimers;
    }

    /**
     * Set the disclaimers value.
     *
     * @param disclaimers the disclaimers value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardLocalizedProperties withDisclaimers(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDisclaimer> disclaimers) {
        this.disclaimers = disclaimers;
        return this;
    }

}
