/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetailsResponseContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetailsResponseContract {
    /**
     * The product property.
     */
    @JsonProperty(value = "Products")
    private List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetails> Products;

    /**
     * Get the product value.
     *
     * @return the product value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetails> Products() {
        return this.Products;
    }

    /**
     * Set the product value.
     *
     * @param Products the product value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetailsResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetailsResponseContract withProducts(List<MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6ProductDetails> Products) {
        this.Products = Products;
        return this;
    }

}
