/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor {
    /**
     * The descriptor property.
     */
    @JsonProperty(value = "descriptor")
    private String descriptor;

    /**
     * The logoUrl property.
     */
    @JsonProperty(value = "logoUrl")
    private String logoUrl;

    /**
     * The key property.
     */
    @JsonProperty(value = "key")
    private String key;

    /**
     * Get the descriptor value.
     *
     * @return the descriptor value
     */
    public String descriptor() {
        return this.descriptor;
    }

    /**
     * Set the descriptor value.
     *
     * @param descriptor the descriptor value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor withDescriptor(String descriptor) {
        this.descriptor = descriptor;
        return this;
    }

    /**
     * Get the logoUrl value.
     *
     * @return the logoUrl value
     */
    public String logoUrl() {
        return this.logoUrl;
    }

    /**
     * Set the logoUrl value.
     *
     * @param logoUrl the logoUrl value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor withLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
        return this;
    }

    /**
     * Get the key value.
     *
     * @return the key value
     */
    public String key() {
        return this.key;
    }

    /**
     * Set the key value.
     *
     * @param key the key value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardDescriptor withKey(String key) {
        this.key = key;
        return this;
    }

}
