/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6SkuSearchResultResponseContract
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6SkuSearchResultResponseContract {
    /**
     * The displaySkuSearchResult property.
     */
    @JsonProperty(value = "displaySkuSearchResult")
    private MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6SkuSearchResultContract displaySkuSearchResult;

    /**
     * Get the displaySkuSearchResult value.
     *
     * @return the displaySkuSearchResult value
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6SkuSearchResultContract displaySkuSearchResult() {
        return this.displaySkuSearchResult;
    }

    /**
     * Set the displaySkuSearchResult value.
     *
     * @param displaySkuSearchResult the displaySkuSearchResult value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6SkuSearchResultResponseContract object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6SkuSearchResultResponseContract withDisplaySkuSearchResult(MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6SkuSearchResultContract displaySkuSearchResult) {
        this.displaySkuSearchResult = displaySkuSearchResult;
        return this;
    }

}
