/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardAlternateId
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardAlternateId {
    /**
     * The idType property.
     */
    @JsonProperty(value = "idType")
    private String idType;

    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Get the idType value.
     *
     * @return the idType value
     */
    public String idType() {
        return this.idType;
    }

    /**
     * Set the idType value.
     *
     * @param idType the idType value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardAlternateId object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardAlternateId withIdType(String idType) {
        this.idType = idType;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardAlternateId object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingBoardAlternateId withValue(String value) {
        this.value = value;
        return this;
    }

}
