/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties {
    /**
     * The language property.
     */
    @JsonProperty(value = "language")
    private String language;

    /**
     * The shortName property.
     */
    @JsonProperty(value = "shortName")
    private String shortName;

    /**
     * The longName property.
     */
    @JsonProperty(value = "longName")
    private String longName;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The logo property.
     */
    @JsonProperty(value = "logo")
    private String logo;

    /**
     * The logoUrl property.
     */
    @JsonProperty(value = "logoUrl")
    private String logoUrl;

    /**
     * Get the language value.
     *
     * @return the language value
     */
    public String language() {
        return this.language;
    }

    /**
     * Set the language value.
     *
     * @param language the language value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties withLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get the shortName value.
     *
     * @return the shortName value
     */
    public String shortName() {
        return this.shortName;
    }

    /**
     * Set the shortName value.
     *
     * @param shortName the shortName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties withShortName(String shortName) {
        this.shortName = shortName;
        return this;
    }

    /**
     * Get the longName value.
     *
     * @return the longName value
     */
    public String longName() {
        return this.longName;
    }

    /**
     * Set the longName value.
     *
     * @param longName the longName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties withLongName(String longName) {
        this.longName = longName;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the logo value.
     *
     * @return the logo value
     */
    public String logo() {
        return this.logo;
    }

    /**
     * Set the logo value.
     *
     * @param logo the logo value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties withLogo(String logo) {
        this.logo = logo;
        return this;
    }

    /**
     * Get the logoUrl value.
     *
     * @return the logoUrl value
     */
    public String logoUrl() {
        return this.logoUrl;
    }

    /**
     * Set the logoUrl value.
     *
     * @param logoUrl the logoUrl value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RatingLocalizedProperties withLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
        return this;
    }

}
