/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7 {
    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * The valueRange property.
     */
    @JsonProperty(value = "valueRange")
    private MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 valueRange;

    /**
     * The modifiedUnitPrice property.
     */
    @JsonProperty(value = "modifiedUnitPrice")
    private Double modifiedUnitPrice;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7 withValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get the valueRange value.
     *
     * @return the valueRange value
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 valueRange() {
        return this.valueRange;
    }

    /**
     * Set the valueRange value.
     *
     * @param valueRange the valueRange value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7 withValueRange(MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ValueRangeV7 valueRange) {
        this.valueRange = valueRange;
        return this;
    }

    /**
     * Get the modifiedUnitPrice value.
     *
     * @return the modifiedUnitPrice value
     */
    public Double modifiedUnitPrice() {
        return this.modifiedUnitPrice;
    }

    /**
     * Set the modifiedUnitPrice value.
     *
     * @param modifiedUnitPrice the modifiedUnitPrice value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7 object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7ClassificationV7 withModifiedUnitPrice(Double modifiedUnitPrice) {
        this.modifiedUnitPrice = modifiedUnitPrice;
        return this;
    }

}
