/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The
 * MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingContextV7
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingContextV7 {
    /**
     * The pricingRulesApplied property.
     */
    @JsonProperty(value = "pricingRulesApplied", access = JsonProperty.Access.WRITE_ONLY)
    private List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7> pricingRulesApplied;

    /**
     * Get the pricingRulesApplied value.
     *
     * @return the pricingRulesApplied value
     */
    public List<MicrosoftMarketplaceServicesDisplayCatalogDCatFDPricingContractsV7PricingRuleV7> pricingRulesApplied() {
        return this.pricingRulesApplied;
    }

}
