/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package microsoft.swagger.codegen.dcatfd.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RankDetails
 * model.
 */
public class MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RankDetails {
    /**
     * The rankName property.
     */
    @JsonProperty(value = "rankName")
    private String rankName;

    /**
     * The supportedFields property.
     */
    @JsonProperty(value = "supportedFields")
    private List<String> supportedFields;

    /**
     * Get the rankName value.
     *
     * @return the rankName value
     */
    public String rankName() {
        return this.rankName;
    }

    /**
     * Set the rankName value.
     *
     * @param rankName the rankName value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RankDetails object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RankDetails withRankName(String rankName) {
        this.rankName = rankName;
        return this;
    }

    /**
     * Get the supportedFields value.
     *
     * @return the supportedFields value
     */
    public List<String> supportedFields() {
        return this.supportedFields;
    }

    /**
     * Set the supportedFields value.
     *
     * @param supportedFields the supportedFields value to set
     * @return the MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RankDetails object itself.
     */
    public MicrosoftMarketplaceServicesDisplayCatalogContractsVersion6RankDetails withSupportedFields(List<String> supportedFields) {
        this.supportedFields = supportedFields;
        return this;
    }

}
